CREATE TABLE "clinic"
(
    "id"                            UUID PRIMARY KEY    NOT NULL DEFAULT gen_random_uuid(),
    "name"                          VARCHAR(255) UNIQUE NOT NULL,
    "email"                         VARCHAR(255)        NOT NULL,
    "city"                          VARCHAR(255)        NOT NULL,
    "address"                       VARCHAR(255)        NOT NULL,
    "phone_number"                  VARCHAR(255)        NOT NULL,
    "clinic_restrictions_enabled" BOOLEAN             NOT NULL DEFAULT FALSE,
    "latitude"                      DOUBLE PRECISION,
    "longitude"                     DOUBLE PRECISION,
    "is_active"                     BOOLEAN             NOT NULL DEFAULT TRUE,
    "owner_id"                      UUID                NOT NULL
);

CREATE TABLE "user"
(
    "id"           UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "email"        VARCHAR(255)     NOT NULL UNIQUE,
    "password"     VARCHAR(255)     NOT NULL,
    "phone_number" VARCHAR(255)     NOT NULL,
    "name"         VARCHAR(255)     NOT NULL,
    "home_address" VARCHAR(255),
    "bulstat"      VARCHAR(255),
    "notes"        TEXT,
    "job_title"    VARCHAR(255)     NOT NULL,
    "is_active"    BOOLEAN          NOT NULL DEFAULT TRUE
);

CREATE TABLE "role"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name"        VARCHAR(255) UNIQUE                                 NOT NULL,
    "description" VARCHAR(255)
);

CREATE TABLE "patient"
(
    "id"                  UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "name"                VARCHAR(255)     NOT NULL,
    "pet_type"            VARCHAR(255)     NOT NULL,
    "microchip"           VARCHAR(255) UNIQUE,
    "pendant"             VARCHAR(255) UNIQUE,
    "passport"            VARCHAR(255) UNIQUE,
    "birthdate"           DATE             NOT NULL,
    "weight"              DECIMAL(5, 2) CHECK (weight >= 0),
    "is_deceased"         BOOLEAN          NOT NULL DEFAULT FALSE,
    "is_neutered"         BOOLEAN          NOT NULL DEFAULT FALSE,
    "patient_access_code" VARCHAR(4)       NOT NULL DEFAULT '0000',
    "note"                TEXT,
    "owner_id"            UUID             NOT NULL
);

CREATE TABLE "vaccination"
(
    "id"          UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "name"        VARCHAR(255)     NOT NULL,
    "start_date"  DATE             NOT NULL,
    "due_date"    DATE             NOT NULL,
    "patient_id"  UUID             NOT NULL,
    "clinic_id" UUID             NOT NULL,
    "user_id"     UUID             NOT NULL
);

CREATE TABLE "discount"
(
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name"               VARCHAR(255)                                        NOT NULL,
    "percent_items"      DECIMAL(5, 2) CHECK (percent_items >= 0),
    "percent_procedures" DECIMAL(5, 2) CHECK (percent_procedures >= 0),
    "clinic_id"        UUID                                                NOT NULL,
    "is_active"          BOOLEAN                                             NOT NULL DEFAULT TRUE
);

CREATE TABLE "note"
(
    "id"          UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "message"     TEXT,
    "date_added"  DATE             NOT NULL,
    "patient_id"  UUID             NOT NULL,
    "clinic_id" UUID             NOT NULL,
    "user_id"     UUID             NOT NULL,
    "is_public"   BOOLEAN          NOT NULL DEFAULT TRUE

);

CREATE TABLE "bill"
(
    "id"               UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "amount"           DECIMAL(9, 2) CHECK (amount >= 0),
    "amount_after_tax" DECIMAL(9, 2) CHECK (amount_after_tax >= 0),
    "paid_amount"      DECIMAL(9, 2)    NOT NULL,
    "remaining_amount" DECIMAL(9, 2)    NOT NULL,
    "has_invoice"      BOOLEAN          NOT NULL DEFAULT FALSE,
    "note"             TEXT,
    "patient_id"       UUID             NOT NULL,
    "clinic_id"      UUID             NOT NULL
);

CREATE TABLE "item"
(
    "id"                 UUID PRIMARY KEY NOT NULL                   DEFAULT gen_random_uuid(),
    "name"               VARCHAR(255)     NOT NULL,
    "description"        VARCHAR(255),
    "available_quantity" BIGINT           NOT NULL                   DEFAULT 0,
    "price"              DECIMAL(9, 2) CHECK (price >= 0),
    "tax_rate_percent"   DECIMAL(5, 2) CHECK (tax_rate_percent >= 0) DEFAULT 20.00,
    "date_added"         DATE             NOT NULL,
    "date_updated"       DATE             NOT NULL,
    "is_active"          BOOLEAN          NOT NULL                   DEFAULT TRUE,
    "clinic_id"        UUID             NOT NULL
);

CREATE TABLE "procedure"
(
    "id"               UUID PRIMARY KEY NOT NULL                   DEFAULT gen_random_uuid(),
    "name"             VARCHAR(255)     NOT NULL,
    "description"      VARCHAR(255),
    "price"            DECIMAL(9, 2) CHECK (price >= 0),
    "tax_rate_percent" DECIMAL(5, 2) CHECK (tax_rate_percent >= 0) DEFAULT 20.00,
    "date_added"       DATE             NOT NULL,
    "date_updated"     DATE             NOT NULL,
    "is_active"        BOOLEAN          NOT NULL                   DEFAULT TRUE,
    "clinic_id"      UUID             NOT NULL
);

CREATE TABLE "billed_item"
(
    "id"               UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "name"             VARCHAR(255)     NOT NULL,
    "description"      VARCHAR(255),
    "billed_price"     DECIMAL(9, 2)    NOT NULL,
    "tax_rate_percent" DECIMAL(5, 2)    NOT NULL,
    "quantity"         BIGINT           NOT NULL DEFAULT 1,
    "billed_date"      DATE             NOT NULL,
    "bill_id"          UUID             NOT NULL,
    "user_id"          UUID             NOT NULL,
    "clinic_id"      UUID             NOT NULL,
    "discount_id"      BIGINT
);

CREATE TABLE "billed_procedure"
(
    "id"               UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    "name"             VARCHAR(255)     NOT NULL,
    "description"      VARCHAR(255),
    "message"          TEXT,
    "billed_price"     DECIMAL(9, 2)    NOT NULL,
    "tax_rate_percent" DECIMAL(5, 2)    NOT NULL,
    "billed_date"      DATE             NOT NULL,
    "bill_id"          UUID             NOT NULL,
    "user_id"          UUID             NOT NULL,
    "clinic_id"      UUID             NOT NULL,
    "discount_id"      BIGINT
);

CREATE TABLE "patient_clinic"
(
    "patient_id"  UUID NOT NULL,
    "clinic_id" UUID NOT NULL
);

CREATE TABLE "user_role_clinic"
(
    "user_id"     UUID   NOT NULL,
    "role_id"     BIGINT NOT NULL,
    "clinic_id" UUID
);

ALTER TABLE "patient_clinic"
    ADD PRIMARY KEY ("patient_id", "clinic_id");

ALTER TABLE "patient_clinic"
    ADD CONSTRAINT "patient_clinic_fk_patient"
        FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "patient_clinic"
    ADD CONSTRAINT "patient_clinic_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "user_role_clinic"
    ADD PRIMARY KEY ("user_id", "role_id", "clinic_id");

ALTER TABLE "user_role_clinic"
    ADD CONSTRAINT "user_role_clinic_fk_user"
        FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "user_role_clinic"
    ADD CONSTRAINT "user_role_clinic_fk_role"
        FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "user_role_clinic"
    ADD CONSTRAINT "user_role_clinic_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "clinic"
    ADD CONSTRAINT "clinic_fk_owner" FOREIGN KEY ("owner_id") REFERENCES "user" ("id");

ALTER TABLE "vaccination"
    ADD CONSTRAINT "vaccination_fk_patient"
        FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "vaccination"
    ADD CONSTRAINT "vaccination_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "vaccination"
    ADD CONSTRAINT "vaccination_fk_user"
        FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "discount"
    ADD CONSTRAINT "discount_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "note"
    ADD CONSTRAINT "note_fk_patient"
        FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "note"
    ADD CONSTRAINT "note_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "note"
    ADD CONSTRAINT "note_fk_user"
        FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "bill"
    ADD CONSTRAINT "bill_fk_patient"
        FOREIGN KEY ("patient_id") REFERENCES "patient" ("id");

ALTER TABLE "bill"
    ADD CONSTRAINT "bill_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "item"
    ADD CONSTRAINT "item_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "procedure"
    ADD CONSTRAINT "procedure_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "billed_item"
    ADD CONSTRAINT "billed_item_fk_bill"
        FOREIGN KEY ("bill_id") REFERENCES "bill" ("id");

ALTER TABLE "billed_item"
    ADD CONSTRAINT "billed_item_fk_user"
        FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "billed_item"
    ADD CONSTRAINT "billed_item_fk_discount"
        FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "billed_item"
    ADD CONSTRAINT "billed_item_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "billed_procedure"
    ADD CONSTRAINT "billed_procedure_fk_bill"
        FOREIGN KEY ("bill_id") REFERENCES "bill" ("id");

ALTER TABLE "billed_procedure"
    ADD CONSTRAINT "billed_procedure_fk_user"
        FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "billed_procedure"
    ADD CONSTRAINT "billed_procedure_fk_discount"
        FOREIGN KEY ("discount_id") REFERENCES "discount" ("id");

ALTER TABLE "billed_procedure"
    ADD CONSTRAINT "billed_procedure_fk_clinic"
        FOREIGN KEY ("clinic_id") REFERENCES "clinic" ("id");

ALTER TABLE "patient"
    ADD CONSTRAINT "patient_fk_user"
        FOREIGN KEY ("owner_id") REFERENCES "user" ("id");

INSERT INTO "user" (id, email, password, phone_number, name, home_address, bulstat, notes, job_title, is_active)
VALUES ('7cec22c6-6079-4b9e-a7e3-6f882ec47ff3', 'admin@opti-pet.com', '123456', '0877779992', 'Dimo Dimov', 'Plovdiv',
        null, null, 'Application Administrator', true);

INSERT INTO "role" ("id", "name", "description")
VALUES (1, 'OWNER', 'Role for Pet Owners'),
       (2, 'VETERINARIAN', 'Role for Veterinarians'),
       (3, 'RECEPTIONIST', 'Role for Receptionist/Cashier/Registration'),
       (4, 'PEOPLE_MANAGER', 'Role for People/Human Resource Manager'),
       (5, 'CLINIC_MANAGER', 'Role for Clinic Managers - pricing, procedures, items and etc'),
       (6, 'ADMINISTRATOR', 'Role for Application Administrator');

INSERT INTO "clinic" ("id", "owner_id", "name", "email", "city", "address", "phone_number",
                        "clinic_restrictions_enabled", "latitude", "longitude", "is_active")
VALUES ('3837ce44-ff3f-4b63-8833-7193be3aa4c3', '7cec22c6-6079-4b9e-a7e3-6f882ec47ff3', 'DEFAULT CLINIC',
        'defaultEmail@email.com', 'Default City', 'Default Address', 'Default Phone Number', false, null, null, true);

INSERT INTO "user_role_clinic" (user_id, role_id, clinic_id)
VALUES ('7cec22c6-6079-4b9e-a7e3-6f882ec47ff3', 1, '3837ce44-ff3f-4b63-8833-7193be3aa4c3'),
       ('7cec22c6-6079-4b9e-a7e3-6f882ec47ff3', 6, '3837ce44-ff3f-4b63-8833-7193be3aa4c3')