package com.opti_pet.backend_app.persistence.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum PetType {
    DOG_AUSTRALIAN_SHEPHERD("Dog-Australian Shepherd / Куче-Австралийска овчарка"),
    DOG_AUSTRALIAN_SILKY_TERRIER("Dog-Australian Silky Terrier / Куче-Австралийски копринен териер"),
    DOG_AUSTRALIAN_TERRIER("Dog-Australian Terrier / Куче-Австралийски териер"),
    DOG_AUSTRALIAN_KELPIE("Dog-Australian Kelpie / Куче-Австралийско келпи "),
    DOG_AUSTRALIAN_SHORT_TAILED_CATTLE_DOG("Dog-Australian Short-Tailed Cattle Dog / Куче-Австралийско късоопашато пастирско куче"),
    DOG_AUSTRALIAN_SHEPHERD_DOG("Dog-Australian Shepherd Dog / Куче-Австралийско пастирско куче"),
    DOG_AUSTRIAN_PINSCHER("Dog-Austrian Pinscher / Куче-Австрийски пинчер"),
    DOG_AZAWAKH("Dog-Azawakh / Куче-Азавак"),
    DOG_AZORES_SHEPHERD("Dog-Azores Shepherd / Куче-Азорски пастир "),
    DOG_AIDI("Dog-Aidi / Куче-Аиди"),
    DOG_AKBASH("Dog-Akbash / Куче-Акбаш"),
    DOG_AKITA_INU("Dog-Akita Inu / Куче-Акита ину "),
    DOG_ALABAI("Dog-Alabai / Куче-Алабай "),
    DOG_ALPINE_DACHSHUND("Dog-Alpine Dachshund / Куче-Алпийски дахсбрак "),
    DOG_ALASKAN_MALAMUTE("Dog-Alaskan Malamute / Куче-Аляски маламут"),
    DOG_ALASKAN_CLAY_KAI("Dog-Alaskan Clay Kai / Куче-Аляско Клей Кай"),
    DOG_AMERICAN_AKITA("Dog-American Akita / Куче-Американска акита"),
    DOG_AMERICAN_BULLDOG("Dog-American Bulldog / Куче-Американски булдог"),
    DOG_AMERICAN_WATER_SPANIEL("Dog-American Water Spaniel / Куче-Американски воден шпаньол"),
    DOG_AMERICAN_HAIRLESS_TERRIER("Dog-American Hairless Terrier / Куче-Американски гол териер"),
    DOG_AMERICAN_COCKER_SPANIEL("Dog-American Cocker Spaniel / Куче-Американски кокер шпаньол "),
    DOG_AMERICAN_HIGHLANDER("Dog-American Highlander / Куче-Американски планинец "),
    DOG_AMERICAN_STAFFORDSHIRE_TERRIER("Dog-American Staffordshire Terrier / Куче-Американски стафордшир териер"),
    DOG_AMERICAN_TOY_FOX_TERRIER("Dog-American Toy Fox Terrier / Куче-Американски той фокстериер"),
    DOG_AMERICAN_FOXHOUND("Dog-American Foxhound / Куче-Американски фоксхаунд"),
    DOG_AMERICAN_DINGO("Dog-American Dingo / Куче-Американско динго "),
    DOG_AMERICAN_ESKIMO_DOG("Dog-American Eskimo Dog / Куче-Американско ескимоско куче "),
    DOG_ANATOLIAN_MASTIFF("Dog-Anatolian Mastiff / Куче-Анадолски мастиф "),
    DOG_ANATOLIAN_SHEEPDOG("Dog-Anatolian Sheepdog / Куче-Анадолско чобанско куче "),
    DOG_ANATOLIAN_SHEPHERD_DOG("Dog-Anatolian Shepherd Dog / Куче-Анатолийска овчарка "),
    DOG_ENGLISH_SHEPHERD("Dog-English Shepherd / Куче-Английска овчарка"),
    DOG_ENGLISH_MASTIFF("Dog-English Mastiff / Куче-Английски мастиф "),
    DOG_ENGLISH_COCKER_SPANIEL("Dog-English Cocker Spaniel / Куче-Английски кокер шпаньол "),
    DOG_ENGLISH_COONHOUND("Dog-English Coonhound / Куче-Английски кунхаунд"),
    DOG_ENGLISH_POINTER("Dog-English Pointer / Куче-Английски пойнтер"),
    DOG_ENGLISH_SETTER("Dog-English Setter / Куче-Английски сетер"),
    DOG_ENGLISH_SPRINGER_SPANIEL("Dog-English Springer Spaniel / Куче-Английски спрингер шпаньол"),
    DOG_ENGLISH_TOY_TERRIER("Dog-English Toy Terrier / Куче-Английски той териер"),
    DOG_ENGLISH_FOXHOUND("Dog-English Foxhound / Куче-Английски фоксхаунд"),
    DOG_ANGLO_FRENCH_MINIATURE_BEAGLE("Dog-Anglo-French Miniature Beagle / Куче-Англо-френско малко гонче"),
    DOG_ANGLO_FRENCH_MEDIUM_BEAGLE("Dog-Anglo-French Medium Beagle / Куче-Англо-френско средно гонче"),
    DOG_APPENZELLER("Dog-Appenzeller / Куче-Апенцелер "),
    DOG_ARYEG_POINTER("Dog-Aryeg Pointer / Куче-Ариежки пойнтер"),
    DOG_ARYEG_MIX("Dog-Aryeg Mix / Куче-Ариежски брак "),
    DOG_ARTOIS_HOUND("Dog-Artois Hound / Куче-Артойс хаунд"),
    DOG_AFGHAN_HOUND("Dog-Afghan Hound / Куче-Афганска хрътка "),
    DOG_AFFENPINSCHER("Dog-Affenpinscher / Куче-Афенпинчер"),
    DOG_BULGARIAN_SHEEPDOG("Dog-Bulgarian Sheepdog / Куче-Българско овчарско куче"),
    DOG_BARACK("Dog-Barack / Куче-Барак"),
    DOG_BARBET("Dog-Barbet / Куче-Барбет"),
    DOG_BASENJI("Dog-Basenji / Куче-Басенджи"),
    DOG_BEDLINGTON_TERRIER("Dog-Bedlington Terrier / Куче-Бедлингтон териер"),
    DOG_BELGIAN_SHEPHERD("Dog-Belgian Shepherd / Куче-Белгийска овчарка"),
    DOG_BELGIAN_GRIFFON("Dog-Belgian Griffon / Куче-Белгийски грифон"),
    DOG_BERGHAM_SHEPHERD("Dog-Bergham Shepherd / Куче-Бергамска овчарка "),
    DOG_BERNESE_MOUNTAIN_DOG("Dog-Bernese Mountain Dog / Куче-Бернски зененхунд"),
    DOG_BEAGLE("Dog-Beagle / Куче-Бигъл"),
    DOG_BEAGLE_HARRIER("Dog-Beagle Harrier / Куче-Бигъл хариер "),
    DOG_BIYI("Dog-Biyi / Куче-Бийи "),
    DOG_BLUETICK_COONHOUND("Dog-Bluetick Coonhound / Куче-Блутикс кунхаунд"),
    DOG_BLOODHOUND("Dog-Bloodhound / Куче-Блъдхаунд"),
    DOG_BOZ("Dog-Boz / Куче-Боз "),
    DOG_BOYKIN_SPANIEL("Dog-Boykin Spaniel / Куче-Бойкин шпаньол "),
    DOG_BOXER("Dog-Boxer / Куче-Боксер "),
    DOG_BOLOGNA("Dog-Bologna / Куче-Болонка "),
    DOG_BORDER_COLLIE("Dog-Border Collie / Куче-Бордър коли "),
    DOG_BORDER_TERRIER("Dog-Border Terrier / Куче-Бордър териер"),
    DOG_BORZAYA("Dog-Borzaya / Куче-Борзая "),
    DOG_BEAUCERON("Dog-Beauceron / Куче-Босерон "),
    DOG_BOSNIAN_BEAGLE("Dog-Bosnian Beagle / Куче-Босненско гонче "),
    DOG_BOSTON_TERRIER("Dog-Boston Terrier / Куче-Бостън териер"),
    DOG_BEARDED_COLLIE("Dog-Bearded Collie / Куче-Брадато коли"),
    DOG_BRAZILIAN_TERRIER("Dog-Brazilian Terrier / Куче-Бразилски териер"),
    DOG_BRAC_SAINT_GERMAIN("Dog-Brac Saint Germain / Куче-Брак Сен Жермен "),
    DOG_BRACCO_ITALIANO("Dog-Bracco Italiano / Куче-Брако италиано "),
    DOG_BRANDELBRACKE("Dog-Brandelbracke / Куче-Брандълбрак "),
    DOG_GRIFFON_BRETON("Dog-Griffon Breton / Куче-Бретански грифон"),
    DOG_BRETON_SPANIEL("Dog-Breton Spaniel / Куче-Бретон шпаньол "),
    DOG_BRIAR("Dog-Briar / Куче-Бриар "),
    DOG_BRICQUET_GRIFFON("Dog-Bricquet Griffon / Куче-Брикет грифон"),
    DOG_BROLHOLMER("Dog-Brolholmer / Куче-Бролхолмер"),
    DOG_BUKOVINA_SHEPHERD_DOG("Dog-Bukovina Shepherd Dog / Куче-Буковинска овчарка"),
    DOG_BULLMASTIFF("Dog-Bullmastiff / Куче-Булмастиф"),
    DOG_BULL_TERRIER("Dog-Bull Terrier / Куче-Бултериер"),
    DOG_MINIATURE_BULL_TERRIER("Dog-Miniature Bull Terrier / Куче-Бултериер миниатюрен"),
    DOG_BOURBON_BRAC("Dog-Bourbon Brac / Куче-Бурбонски брак"),
    DOG_WHITE_GERMAN_SHEPHERD_DOG("Dog-White German Shepherd Dog / Куче-Бяла Немска овчарка"),
    DOG_WHITE_SHEPHERD_DOG("Dog-White Shepherd Dog / Куче-Бяла овчарка "),
    DOG_WEIMARANER("Dog-Weimaraner / Куче-Ваймаранер "),
    DOG_WESTPHALIAN_BEAGLE("Dog-Westphalian Beagle / Куче-Вестфалско гонче"),
    DOG_VINCI("Dog-Vinci / Куче-Винчи"),
    DOG_VOLPINO_ITALIANO("Dog-Volpino Italiano / Куче-Волпино италиано"),
    DOG_SMOOTH_HAIRED_RETRIEVER("Dog-Smooth-haired Retriever / Куче-Гладкокосмест ретривър"),
    DOG_GLEN_OF_IMAAL_TERRIER("Dog-Glen of Imaal Terrier / Куче-Глен оф имаал териер "),
    DOG_GOLDEN_RETRIEVER("Dog-Golden Retriever / Куче-Голдън ретривър "),
    DOG_LARGE_VENDEEN_GRIFFON("Dog-Large Vendeen Griffon / Куче-Голям вандейски грифон"),
    DOG_LARGE_MUNSTERLANDER("Dog-Large Munsterlander / Куче-Голям мюнстерландер "),
    DOG_LARGE_POODLE("Dog-Large Poodle / Куче-Голям Пудел "),
    DOG_LARGE_ANGLO_FRENCH_WHITE_ORANGE_BEAGLE("Dog-Large Anglo-French White-Orange Beagle / Куче-Голямо англо-френско бяло-оранжево гонче"),
    DOG_LARGE_ANGLO_FRENCH_WHITE_RED_BEAGLE("Dog-Large Anglo-French White-Red beagle / Куче-Голямо англо-френско бяло-червено гонче"),
    DOG_GREAT_ANGLO_FRENCH_BLACK_AND_WHITE_BEAGLE("Dog-Great Anglo-French Black and White Beagle / Куче-Голямо англо-френско бяло-черно гонче"),
    DOG_GREAT_ANGLO_FRENCH_TRICOLOUR_BEAGLE("Dog-Great Anglo-French Tricolour Beagle / Куче-Голямо англо-френско трицветно гонче"),
    DOG_GREAT_GASCON_SAINT_ETIENNE_DE_SAINT_GOBAIN("Dog-Great Gascon Saint-Etienne-de-Saint-Gobain / Куче-Голямо гасконско сентонжуа"),
    DOG_GREAT_BLUE_GASCON_BEAGLE("Dog-Great Blue Gascon Beagle / Куче-Голямо синьо гасконско гонче "),
    DOG_GREAT_SWISS_MOUNTAIN_DOG("Dog-Great Swiss Mountain Dog / Куче-Голямо швейцарско планинско куче"),
    DOG_GREENLAND_DOG("Dog-Greenland Dog / Куче-Гренландско куче "),
    DOG_GREYHOUND("Dog-Greyhound / Куче-Грейхаунд"),
    DOG_GRIFFON_CORTALLAS("Dog-Griffon Cortallas / Куче-Грифон корталас "),
    DOG_GRIFFON_NIVERNAIS("Dog-Griffon Nivernais / Куче-Грифон нивернайс "),
    DOG_DACHSHUND("Dog-Dachshund / Куче-Дакел "),
    DOG_DALMATIAN("Dog-Dalmatian / Куче-Далматинец "),
    DOG_DANDY_DIAMOND_TERRIER("Dog-Dandy Diamond Terrier / Куче-Денди даймънт териер"),
    DOG_DICULAK("Dog-Diculak / Куче-Дикулак "),
    DOG_DOBERMAN("Dog-Doberman / Куче-Доберман "),
    DOG_DOGO_ARGENTINO("Dog-Dogo Argentino / Куче-Дого Аржентино"),
    DOG_DREVER("Dog-Drever / Куче-Древер"),
    DOG_DUNKER("Dog-Dunker / Куче-Дюнкер "),
    DOG_EURASIER("Dog-Eurasier / Куче-Евразиер "),
    DOG_ENTLEBUCHER_SENNENHUND("Dog-Entlebucher Sennenhund / Куче-Ентлебухер Зененхунд"),
    DOG_BLUE_PICARDY_SPANIEL("Dog-Blue Picardy Spaniel / Куче-Епаньол син Пикард "),
    DOG_ESTREL_MOUNTAIN_DOG("Dog-Estrel Mountain Dog / Куче-Ещрелско планинско куче "),
    DOG_AIREDALE_TERRIER("Dog-Airedale Terrier / Куче-Еърдейл териер"),
    DOG_YELLOW_BLACK_FACED_SOUTHERN_GREYHOUND("Dog-Yellow Black-faced Southern Greyhound / Куче-Жълта черномуцунеста южна хрътка "),
    DOG_TAN("Dog-Tan / Куче-Загар "),
    DOG_WEST_SIBERIAN_LAIKA("Dog-West Siberian Laika / Куче-Западносибирска лайка"),
    DOG_WEST_HIGHLAND_WHITE_TERRIER("Dog-West Highland White Terrier / Куче-Западнохайландски бял териер"),
    DOG_ZWERGBORETS("Dog-Zwergborets / Куче-Звероборец "),
    DOG_ZERDAVA("Dog-Zerdava / Куче-Зердава "),
    DOG_IBIZAN_GREYHOUND("Dog-Ibizan Greyhound / Куче-Ибиска хрътка "),
    DOG_IRISH_WATER_SPANIEL("Dog-Irish Water Spaniel / Куче-Ирландски воден шпаньол"),
    DOG_IRISH_WOLFHOUND("Dog-Irish Wolfhound / Куче-Ирландски вълкодав"),
    DOG_IRISH_SETTER("Dog-Irish Setter / Куче-Ирландски сетер"),
    DOG_IRISH_TERRIER("Dog-Irish Terrier / Куче-Ирландски териер"),
    DOG_IRISH_RED_SETTER("Dog-Irish Red Setter / Куче-Ирландски червен сетер"),
    DOG_IRISH_RED_AND_WHITE_SETTER("Dog-Irish Red and White Setter / Куче-Ирландски червено-бял сетер"),
    DOG_ICELANDIC_SHEEPDOG("Dog-Icelandic Sheepdog / Куче-Исландска овчарка"),
    DOG_SPANISH_HOUND("Dog-Spanish Hound / Куче-Испанска хрътка "),
    DOG_SPANISH_GREYHOUND("Dog-Spanish Greyhound / Куче-Испански грейхаунд"),
    DOG_SPANISH_BLOODHOUND("Dog-Spanish Bloodhound / Куче-Испански кръвоследник"),
    DOG_SPANISH_MASTIFF("Dog-Spanish Mastiff / Куче-Испански мастиф"),
    DOG_SPANISH_POINTER("Dog-Spanish Pointer / Куче-Испански пойнтер"),
    DOG_SPANISH_WATER_DOG("Dog-Spanish Water Dog / Куче-Испанско водно куче"),
    DOG_ISTRIAN_SHORTHAIRED_HOUND("Dog-Istrian Shorthaired Hound / Куче-Истрийска късокосместа хрътка "),
    DOG_ISTRIAN_WIREHAIRED_BEAGLE("Dog-Istrian Wirehaired Beagle / Куче-Истрийско твърдокосместо гонче "),
    DOG_ITALIAN_GREYHOUND("Dog-Italian Greyhound / Куче-Италиански грейхаунд "),
    DOG_ITALIAN_HOUND("Dog-Italian Hound / Куче-Италианска хрътка "),
    DOG_JAMTLAND_SHEEPDOG("Dog-Jämtland Sheepdog / Куче-Йемтландска лайка "),
    DOG_YORKSHIRE_TERRIER("Dog-Yorkshire Terrier / Куче-Йоркширски териер "),
    DOG_CAVALIER_KING_CHARLES_SPANIEL("Dog-Cavalier King Charles Spaniel / Куче-Кавалер Кинг Чарлз шпаньол "),
    DOG_CAUCASIAN_SHEPHERD_DOG("Dog-Caucasian Shepherd Dog / Куче-Кавказка овчарка"),
    DOG_KARAKACHAN_DOG("Dog-Karakachan Dog / Куче-Каракачанско куче"),
    DOG_CANADIAN_ESKIMO_DOG("Dog-Canadian Eskimo Dog / Куче-Канадско ескимоско куче"),
    DOG_CANARY_FIGHTING_DOG("Dog-Canary Fighting Dog / Куче-Канарско бойно куче"),
    DOG_CANARY_PODENGO("Dog-Canary Podengo / Куче-Канарско поденго "),
    DOG_KANGAL("Dog-Kangal / Куче-Кангал"),
    DOG_CANE_CORSO("Dog-Cane Corso / Куче-Кане Корсо "),
    DOG_KARAMAN("Dog-Karaman / Куче-Караман "),
    DOG_KARAYAKA("Dog-Karayaka / Куче-Караяка "),
    DOG_KAREL_BEAR_DOG("Dog-Karel Bear Dog / Куче-Карелско мечо куче "),
    DOG_CARPATHIAN_SHEPHERD_DOG("Dog-Carpathian Shepherd Dog / Куче-Карпатска овчарка"),
    DOG_KARS("Dog-Kars / Куче-Карс "),
    DOG_CASTRO_LABREUIL_SHEPHERD("Dog-Castro-Labreuil Shepherd / Куче-Кастро-лаборейска овчарка "),
    DOG_CATALAN_SHEPHERD("Dog-Catalan Shepherd / Куче-Каталанска овчарка "),
    DOG_BROWN_GERMAN_SHEPHERD("Dog-Brown German Shepherd / Куче-Кафява Немска овчарка"),
    DOG_KEESHOND("Dog-Keeshond / Куче-Кеесхонд "),
    DOG_KERRY_BLUE_TERRIER("Dog-Kerry Blue Terrier / Куче-Кери син териер "),
    DOG_CAIN_TERRIER("Dog-Cain Terrier / Куче-Кеърнтериер"),
    DOG_KING_CHARLES_SPANIEL("Dog-King Charles Spaniel / Куче-Кинг Чарлз шпаньол "),
    DOG_CHINESE_HAIRLESS_DOG("Dog-Chinese Hairless Dog / Куче-Китайско голо куче"),
    DOG_CLUMBER_SPANIEL("Dog-Clumber Spaniel / Куче-Кламбър шпаньол "),
    DOG_COYKER("Dog-Coyker / Куче-Койкер "),
    DOG_COLLIE("Dog-Collie / Куче-Коли"),
    DOG_KOMONDOR("Dog-Komondor / Куче-Комондор"),
    DOG_KOREAN_JINDO("Dog-Korean Jindo / Куче-Корейско джиндо"),
    DOG_COTON_DE_TULEAR("Dog-Coton de Tulear / Куче-Котон де тулеар"),
    DOG_COYUN("Dog-Coyun / Куче-Коюн "),
    DOG_FOOTED_SHEEPDOG("Dog-Footed Sheepdog / Куче-Крашка овчарка"),
    DOG_KROMFORLANDER("Dog-Kromforlander / Куче-Кромфорлендер"),
    DOG_KUVASS("Dog-Kuvass / Куче-Кувас "),
    DOG_CURLY_COATED_RETRIEVER("Dog-Curly-Coated Retriever / Куче-Къдравокосмест ретривър"),
    DOG_SHORT_COATED_COLLIE("Dog-Short-Coated Collie / Куче-Късокосместо коли"),
    DOG_KYUSHU("Dog-Kyushu / Куче-Кюшу "),
    DOG_LABRADOR_RETRIEVER("Dog-Labrador Retriever / Куче-Лабрадор ретривър"),
    DOG_LAGOTO_ROMAGNOLO("Dog-Lagoto Romagnolo / Куче-Лагото романьоло "),
    DOG_LANDSIRE("Dog-Landsire / Куче-Ландзеер "),
    DOG_LANCASHIRE_HEELER("Dog-Lancashire Heeler / Куче-Ланкаширски хилър "),
    DOG_LAPPONIAN_HILLER("Dog-Lapponian Hiller / Куче-Лапониан хилер "),
    DOG_LAKELAND_TERRIER("Dog-Lakeland Terrier / Куче-Лейкланд териер"),
    DOG_LEONBERGER("Dog-Leonberger / Куче-Леонбергер"),
    DOG_CATAHULA_LEOPARD("Dog-Catahula Leopard / Куче-Леопардова катахула"),
    DOG_LOFCHEN("Dog-Lofchen / Куче-Лофчен "),
    DOG_LHASA_APSO("Dog-Lhasa Apso / Куче-Лхаса апсо"),
    DOG_MAJORCA_SHEPHERD_DOG("Dog-Majorca Shepherd Dog / Куче-Майоркска овчарка "),
    DOG_MAJORCA_MASTIFF("Dog-Majorca Mastiff / Куче-Майоркски мастиф "),
    DOG_PETIT_GASCON_SAINT_GOBAIN("Dog-Petit Gascon Saint-Gobain / Куче-Малко гасконско сентонжуа"),
    DOG_PETIT_BLUE_GASCON_BEAGLE("Dog-Petit Blue Gascon Beagle / Куче-Малко синьо гасконско гонче "),
    DOG_SMALL_SWISS_BEAGLE("Dog-Small Swiss Beagle / Куче-Малко швейцарско гонче "),
    DOG_MALTESE_BOLOGNESE("Dog-Maltese Bolognese / Куче-Малтийска болонка "),
    DOG_SMALL_BASSET_GRIFFON_VENDEEN("Dog-Small Basset Griffon Vendeen / Куче-Малък вандейски басет-грифон"),
    DOG_SMALL_VENDEEN_GRIFFON("Dog-Small Vendeen Griffon / Куче-Малък вандейски грифон"),
    DOG_SMALL_MUNSTERLANDER("Dog-Small Munsterlander / Куче-Малък мюнстерландер "),
    DOG_SMALL_GERMAN_SPITZ("Dog-Small German Spitz / Куче-Малък немски шпиц "),
    DOG_SMALL_POODLE("Dog-Small Poodle / Куче-Малък пудел"),
    DOG_MANCHESTER_TERRIER("Dog-Manchester Terrier / Куче-Манчестър териер"),
    DOG_MAREMMA_SHEEPDOG("Dog-Maremma Sheepdog / Куче-Маремска овчарка "),
    DOG_SOFT_HAIRED_WHEATEN_TERRIER("Dog-Soft-haired Wheaten Terrier / Куче-Мекокосмест пшеничен териер "),
    DOG_MEXICAN_HAIRLESS_DOG("Dog-Mexican Hairless Dog / Куче-Мексиканско голо куче "),
    DOG_MINI_PINSCHER("Dog-Mini Pinscher / Куче-Мини пинчер"),
    DOG_MINI_SCHNAUZER("Dog-Mini Schnauzer / Куче-Мини шнауцер"),
    DOG_MINIATURE_GERMAN_SPITZ("Dog-Miniature German Spitz / Куче-Миниатюрен немски шпиц "),
    DOG_MINIATURE_POODLE("Dog-Miniature Poodle / Куче-Миниатюрен пудел"),
    DOG_MINIATURE_SCHNAUZER("Dog-Miniature Schnauzer / Куче-Миниатюрен шнауцер"),
    DOG_MIORIT("Dog-Miorit / Куче-Миорит "),
    DOG_PUG("Dog-Pug / Куче-Мопс"),
    DOG_NEAPOLITAN_MASTIFF("Dog-Neapolitan Mastiff / Куче-Неаполитански мастиф"),
    DOG_GERMAN_SHEPHERD("Dog-German Shepherd / Куче-Немска овчарка "),
    DOG_GREAT_DANE("Dog-Great Dane / Куче-Немски дог "),
    DOG_GERMAN_LONGHAIRED_POINTER("Dog-German Longhaired Pointer / Куче-Немски дългокосмест пойнтер"),
    DOG_GERMAN_SHORTHAIRED_POINTER("Dog-German Shorthaired Pointer / Куче-Немски късокосмест пойнтер"),
    DOG_GERMAN_PINSCHER("Dog-German Pinscher / Куче-Немски пинчер "),
    DOG_GERMAN_WIREHAIRED_POINTER("Dog-German Wirehaired Pointer / Куче-Немски твърдокосмест пойнтер"),
    DOG_GERMAN_SPANIEL("Dog-German Spaniel / Куче-Немски шпаньол"),
    DOG_GERMAN_SPITZ("Dog-German Spitz / Куче-Немски шпиц "),
    DOG_NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER("Dog-Nova Scotia Duck Tolling Retriever / Куче-Новошотландски ретривър "),
    DOG_NORBOTTENSPETS("Dog-Norbottenspets / Куче-Норботенспетс"),
    DOG_NORWEGIAN_BUHUND("Dog-Norwegian Buhund / Куче-Норвежки бухунд"),
    DOG_NORWEGIAN_ELKHOUND("Dog-Norwegian Elkhound / Куче-Норвежки елкхунд "),
    DOG_NORWEGIAN_LUNDEHUND("Dog-Norwegian Lundehund / Куче-Норвежки лундехунд"),
    DOG_NORWEGIAN_BLACK_ELKHOUND("Dog-Norwegian Black Elkhound / Куче-Норвежки черен елкхунд"),
    DOG_NORWICH_TERRIER("Dog-Norwich Terrier / Куче-Норички териер "),
    DOG_BASSET_NORMAND("Dog-Basset Normand / Куче-Нормандски басет"),
    DOG_NORFOLK_TERRIER("Dog-Norfolk Terrier / Куче-Норфолкски териер "),
    DOG_NEWFOUNDLAND("Dog-Newfoundland / Куче-Нюфаундленд "),
    DOG_OYRAZIR("Dog-Oyrazir / Куче-Ойразир"),
    DOG_OTTERHOUND("Dog-Otterhound / Куче-Отърхаунд "),
    DOG_PAPILLON("Dog-Papillon / Куче-Папийон"),
    DOG_PARSON_RUSSELL_TERRIER("Dog-Parson Russell Terrier / Куче-Парсън ръсел териер"),
    DOG_PATTERDALE_TERRIER("Dog-Patterdale Terrier / Куче-Патърдейл териер"),
    DOG_PEKINGESE("Dog-Pekingese / Куче-Пекинез"),
    DOG_PERUVIAN_HAIRLESS_DOG("Dog-Peruvian Hairless Dog / Куче-Перуанско голо куче "),
    DOG_PICARDY_SHEEPDOG("Dog-Picardy Sheepdog / Куче-Пикардийска овчарка"),
    DOG_PICARDY_SPANIEL("Dog-Picardy Spaniel / Куче-Пикардски шпаньол "),
    DOG_PYRENEAN_SHEEPDOG("Dog-Pyrenean Sheepdog / Куче-Пиренейска овчарка"),
    DOG_PYRENEAN_MASTIFF("Dog-Pyrenean Mastiff / Куче-Пиренейски мастиф"),
    DOG_PYRENEAN_BERGER("Dog-Pyrenean Berger / Куче-Пиренейско берже "),
    DOG_PYRENEAN_MOUNTAIN_DOG("Dog-Pyrenean Mountain Dog / Куче-Пиренейско планинско куче"),
    DOG_AIRES_MOUNTAIN_DOG("Dog-Aires Mountain Dog / Куче-Планинско куче от Айрес "),
    DOG_PLOT_HOUND("Dog-Plot Hound / Куче-Плот хаунд"),
    DOG_POLISH_LOWLAND_SHEEPDOG("Dog-Polish Lowland Sheepdog / Куче-Полска низинна овчарка"),
    DOG_POLISH_TATRA_SHEEPDOG("Dog-Polish Tatra Sheepdog / Куче-Полска татренска овчарка "),
    DOG_POLISH_GREYHOUND("Dog-Polish Greyhound / Куче-Полска хрътка "),
    DOG_POLISH_SPANIEL("Dog-Polish Spaniel / Куче-Полски шпаньол "),
    DOG_POLISH_HUNTING_DOG("Dog-Polish Hunting Dog / Куче-Полско ловно куче"),
    DOG_POMERANIAN("Dog-Pomeranian / Куче-Померан"),
    DOG_POMSKY("Dog-Pomsky / Куче-Помски "),
    DOG_PONT_AUDEMARS_PIED_PIPER_SPANIEL("Dog-Pont-Audemars Pied Piper Spaniel / Куче-Понт-Одемерски шпаньол "),
    DOG_PORCELAIN("Dog-Porcelain / Куче-Порселен "),
    DOG_PORTUGUESE_POINTER("Dog-Portuguese Pointer / Куче-Португалски пойнтер"),
    DOG_PORTUGUESE_WATER_DOG("Dog-Portuguese Water Dog / Куче-Португалско водно куче "),
    DOG_PORTUGUESE_PODENGO("Dog-Portuguese Podengo / Куче-Португалско поденго "),
    DOG_POITOU_CHARENTES("Dog-Poitou-Charentes / Куче-Пуатвен"),
    DOG_POODLE("Dog-Poodle / Куче-Пудел "),
    DOG_POODLE_POINTER("Dog-Poodle Pointer / Куче-Пуделпойнтер "),
    DOG_PULI("Dog-Puli / Куче-Пули "),
    DOG_PUMI("Dog-Pumi / Куче-Пуми "),
    DOG_RAT_TERRIER("Dog-Rat Terrier / Куче-Рат териер"),
    DOG_RAFEIRO_DE_ALENTEJO("Dog-Rafeiro de Alentejo / Куче-Рафейро де Алентехо "),
    DOG_REDBONE_COONHOUND("Dog-Redbone Coonhound / Куче-Редбон кунхаунд"),
    DOG_GIANT_SCHNAUZER("Dog-Giant Schnauzer / Куче-Ризеншнауцер "),
    DOG_RHODESIAN_RIDGEBACK("Dog-Rhodesian Ridgeback / Куче-Родезийски риджбек"),
    DOG_ROTTWEILER("Dog-Rottweiler / Куче-Ротвайлер"),
    DOG_RUSSIAN_TOY_TERRIER("Dog-Russian Toy Terrier / Куче-Руски той териер"),
    DOG_RUSSELL_TERRIER("Dog-Russell Terrier / Куче-Ръсел териер"),
    DOG_SALUKI("Dog-Saluki / Куче-Салуки "),
    DOG_SAMOYED("Dog-Samoyed / Куче-Самоед"),
    DOG_SAINT_BERNARD("Dog-Saint Bernard / Куче-Санбернар"),
    DOG_SAARLOOS_WOLFDOG("Dog-Saarloos Wolfdog / Куче-Сарлосово вълче куче "),
    DOG_SIBERIAN_HUSKY("Dog-Siberian Husky / Куче-Сибирско хъски"),
    DOG_SILIHAM_TERRIER("Dog-Siliham Terrier / Куче-Силихам териер "),
    DOG_BLUE_GASCON_BASSET_HOUND("Dog-Blue Gascon Basset Hound / Куче-Син гасконски басет"),
    DOG_BLUE_GASCON_GRIFFON("Dog-Blue Gascon Griffon / Куче-Син гасконски грифон"),
    DOG_SICILIAN_GREYHOUND("Dog-Sicilian Greyhound / Куче-Сицилианска хрътка "),
    DOG_SKY_TERRIER("Dog-Sky Terrier / Куче-Скай териер"),
    DOG_SLOVAK_WIREHAIRED_POINTER("Dog-Slovak Wirehaired Pointer / Куче-Словашки грубокосмест пойнтер"),
    DOG_SLOVAKIAN_KOPOV("Dog-Slovakian Kopov / Куче-Словашки копов "),
    DOG_SLOVAK_CHUVACH("Dog-Slovak Chuvach / Куче-Словашки чувач "),
    DOG_SLAVIC_KOPOJ("Dog-Slavic Kopoj / Куче-Словенски копой "),
    DOG_SLOUGI("Dog-Slougi / Куче-Слоуги "),
    DOG_SPINONE_ITALIANO("Dog-Spinone Italiano / Куче-Спиноне италиано "),
    DOG_SPORTING_LUCAS_TERRIER("Dog-Sporting Lucas Terrier / Куче-Спортинг лукас териер"),
    DOG_MEDIUM_GERMAN_SPITZ("Dog-Medium German Spitz / Куче-Среден немски шпиц "),
    DOG_SERBIAN_BEAGLE("Dog-Serbian Beagle / Куче-Сръбско гонче"),
    DOG_SERBIAN_TRICOLOR_BEAGLE("Dog-Serbian Tricolor Beagle / Куче-Сръбско трицветно гонче"),
    DOG_STABIHUN("Dog-Stabihun / Куче-Стабихун "),
    DOG_STANDARD_SCHNAUZER("Dog-Standard Schnauzer / Куче-Стандартен шнауцер"),
    DOG_OLD_ENGLISH_SHEEPDOG("Dog-Old English Sheepdog / Куче-Староанглийска овчарка "),
    DOG_OLD_GERMAN_POINTER("Dog-Old German Pointer / Куче-Стародатски пойнтер"),
    DOG_STAFFORDSHIRE_BULL_TERRIER("Dog-Staffordshire Bull Terrier / Куче-Стафордширски бултериер "),
    DOG_STEPHENS_STOCK_DOG("Dog-Stephens Stock Dog / Куче-Стефенс Сток дог "),
    DOG_SUSSEX_SPANIEL("Dog-Sussex Spaniel / Куче-Съсекс шпаньол"),
    DOG_TAZY("Dog-Tazy / Куче-Тазъй "),
    DOG_THAI_RIDGEBACK("Dog-Thai Ridgeback / Куче-Тайландски риджбек"),
    DOG_TARSUS_CHATALBURUN("Dog-Tarsus Chatalburun / Куче-Тарсус Чаталбурун "),
    DOG_WIREHAIRED_VIZSLA("Dog-Wirehaired Vizsla / Куче-Твърдокосместа визла "),
    DOG_TEDDY_ROOSEVELT_TERRIER("Dog-Teddy Roosevelt Terrier / Куче-Теди Рузвелт териер"),
    DOG_TENDERFIELD_TERRIER("Dog-Tenderfield Terrier / Куче-Тендерфийлд териер"),
    DOG_TIBETAN_MASTIFF("Dog-Tibetan Mastiff / Куче-Тибетски мастиф "),
    DOG_TIBETAN_TERRIER("Dog-Tibetan Terrier / Куче-Тибетски териер"),
    DOG_TIBETAN_SPANIEL("Dog-Tibetan Spaniel / Куче-Тибетски шпаньол"),
    DOG_TYROLEAN_HOUND("Dog-Tyrolean Hound / Куче-Тиролска хрътка "),
    DOG_TOY_MANCHESTER_TERRIER("Dog-Toy Manchester Terrier / Куче-Той Манчестър териер"),
    DOG_TOY_FOX_TERRIER("Dog-Toy Fox Terrier / Куче-Той Фокс териер"),
    DOG_TORNJAK("Dog-Tornjak / Куче-Торняк "),
    DOG_TOSA("Dog-Tosa / Куче-Тоса "),
    DOG_TRANSYLVANIAN_BEAGLE("Dog-Transylvanian Beagle / Куче-Трансилвански брак "),
    DOG_TREEING_WALKER_COONHOUND("Dog-Treeing Walker Coonhound / Куче-Триинг уолкър кунхаунд"),
    DOG_TRICOLOR_BEAGLE("Dog-Tricolor Beagle / Куче-Трицветно гонче "),
    DOG_TURKISH_TAZY("Dog-Turkish Tazy / Куче-Турски Тазъй "),
    DOG_CARDIGAN_WELSH_CORGI("Dog-Cardigan Welsh Corgi / Куче-Уелско корги кардиган"),
    DOG_PEMBROKE_WELSH_CORGI("Dog-Pembroke Welsh Corgi / Куче-Уелско корги пембрук"),
    DOG_WELSH_SPRINGER_SPANIEL("Dog-Welsh Springer Spaniel / Куче-Уелски спрингер шпаньол"),
    DOG_WELSH_TERRIER("Dog-Welsh Terrier / Куче-Уелски териер"),
    DOG_WHIPPET("Dog-Whippet / Куче-Уипет"),
    DOG_HUNGARIAN_VIZSLA("Dog-Hungarian Vizsla / Куче-Унгарска визла "),
    DOG_HUNGARIAN_GREYHOUND("Dog-Hungarian Greyhound / Куче-Унгарска хрътка "),
    DOG_HUNGARIAN_MUDI("Dog-Hungarian Mudi / Куче-Унгарско муди "),
    DOG_URUGUAYAN_CIMARRON_MOLOSSER("Dog-Uruguayan Cimarron Molosser / Куче-Уругвайски симарон молозер"),
    DOG_UTONAGAN("Dog-Utonagan / Куче-Утонаган"),
    DOG_PHARAOHS_DOG("Dog-Pharaohs Dog / Куче-Фараоново куче"),
    DOG_FILA_BRASILEIRO("Dog-Fila Brasileiro / Куче-Фила бразилейро "),
    DOG_FINNISH_GREYHOUND("Dog-Finnish Greyhound / Куче-Финландска хрътка "),
    DOG_FINNISH_LAPPHUND("Dog-Finnish Lapphund / Куче-Финландски лапхунд "),
    DOG_FINNISH_SPITZ("Dog-Finnish Spitz / Куче-Финландски шпиц "),
    DOG_FINO_A_TONYA("Dog-Fino à Tonya / Куче-Фино от Тоня "),
    DOG_BOUVIER_DFLANDERS("Dog-Bouvier dFlanders / Куче-Фландърско бувие"),
    DOG_SHORTHAIRED_FOX_TERRIER("Dog-Shorthaired Fox Terrier / Куче-Фокстериер късокосмест "),
    DOG_WIREHAIRED_FOX_TERRIER("Dog-Wirehaired Fox Terrier / Куче-Фокстериер твърдокосмест"),
    DOG_FORMOSAUN("Dog-Formosaun / Куче-Формосан"),
    DOG_FRENCH_BEAGLE("Dog-French Beagle / Куче-Френска болонка "),
    DOG_FRENCH_BULLDOG("Dog-French Bulldog / Куче-Френски булдог"),
    DOG_FRENCH_MASTIFF("Dog-French Mastiff / Куче-Френски мастиф "),
    DOG_FRENCH_NARC("Dog-French Narc / Куче-Френски нарак"),
    DOG_FRENCH_SPANIEL("Dog-French Spaniel / Куче-Френски шпаньол "),
    DOG_FRENCH_SHEPHERD_DOG("Dog-French Shepherd Dog / Куче-Френско овчарче"),
    DOG_FRENCH_RED_AND_WHITE_BEAGLE("Dog-French Red and White Beagle / Куче-Френско червенобяло гонче "),
    DOG_FRENCH_BLACK_AND_WHITE_BEAGLE("Dog-French Black and White Beagle / Куче-Френско чернобяло гонче "),
    DOG_FRIESIAN_WATER_DOG("Dog-Friesian Water Dog / Куче-Фризийско водно куче"),
    DOG_HAVANESE_DOG("Dog-Havanese Dog / Куче-Хаванска болонка "),
    DOG_HAMILTON_STOVER("Dog-Hamilton Stover / Куче-Хамилтонстьовер "),
    DOG_CANAAN_DOG("Dog-Canaan Dog / Куче-Ханаанско куче"),
    DOG_HANOVERIAN_BLOODHOUND("Dog-Hanoverian Bloodhound / Куче-Хановерски кръвоследник"),
    DOG_HARRIER("Dog-Harrier / Куче-Хариър "),
    DOG_HOVAWART("Dog-Hovawart / Куче-Ховаварт "),
    DOG_HOKKAIDO("Dog-Hokkaido / Куче-Хокайдо"),
    DOG_DUTCH_SHEPHERD("Dog-Dutch Shepherd / Куче-Холандска овчарка "),
    DOG_DUTCH_POMERANIAN("Dog-Dutch Pomeranian / Куче-Холандски птичар"),
    DOG_DUTCH_SMAUSHOUND("Dog-Dutch Smaushound / Куче-Холандски смаусхонд "),
    DOG_CROATIAN_SHEPHERD("Dog-Croatian Shepherd / Куче-Хърватска овчарка"),
    DOG_CHOW_CHOW("Dog-Chow Chow / Куче-Чау-чау"),
    DOG_CHAPAR("Dog-Chapar / Куче-Чапар "),
    DOG_BLACK_RUSSIAN_TERRIER("Dog-Black Russian Terrier / Куче-Черен руски териер "),
    DOG_BLACK_GERMAN_SHEPHERD("Dog-Black German Shepherd / Куче-Черна Немска овчарка "),
    DOG_MONTENEGRIN_MOUNTAIN_HOUND("Dog-Montenegrin Mountain Hound / Куче-Черногорска планинска хрътка "),
    DOG_BLACK_AND_TAN_COONHOUND("Dog-Black-and-tan Coonhound / Куче-Чернокафяв кунхаунд "),
    DOG_BLACK_FACED_DOG("Dog-Black-faced Dog / Куче-Черномуцунесто куче"),
    DOG_CHESAPEAKE_BAY_RETRIEVER("Dog-Chesapeake Bay Retriever / Куче-Чесапийк бей ретривър"),
    DOG_CZECH_WOLFHOUND("Dog-Czech Wolfhound / Куче-Чешки вълчак "),
    DOG_CZECH_TERRIER("Dog-Czech Terrier / Куче-Чешки териер"),
    DOG_CZECH_FUSEK("Dog-Czech Fusek / Куче-Чешки фусек "),
    DOG_CHINOOK("Dog-Chinook / Куче-Чинуук "),
    DOG_CHIHUAHUA("Dog-Chihuahua / Куче-Чихуахуа "),
    DOG_CHAPENDAUX("Dog-Chapendaux / Куче-Шапендоус "),
    DOG_SHAR_PEI("Dog-Shar-Pei / Куче-Шар-пей"),
    DOG_SHAR_PANINEN("Dog-Shar-Paninen / Куче-Шарпланинец"),
    DOG_SWEDISH_VALLHUND("Dog-Swedish Vallhund / Куче-Шведски валхунд "),
    DOG_SWEDISH_LAPPHUND("Dog-Swedish Lapphund / Куче-Шведски лапхунд"),
    DOG_SWISS_BEAGLE("Dog-Swiss Beagle / Куче-Швейцарско гонче "),
    DOG_SHETLAND_SHEEPDOG("Dog-Shetland Sheepdog / Куче-Шетландска овчарка "),
    DOG_SHIH_TZU("Dog-Shih Tzu / Куче-Ших тцу "),
    DOG_SHIBA_INU("Dog-Shiba inu / Куче-Шиба ину"),
    DOG_SHIKOKU("Dog-Shikoku / Куче-Шикоку"),
    DOG_SCHILLERSTOWER("Dog-Schillerstower / Куче-Шилерстьовер "),
    DOG_SCHIPPERKE("Dog-Schipperke / Куче-Шиперке"),
    DOG_SCOTTISH_DEERHOUND("Dog-Scottish Deerhound / Куче-Шотландски диърхаунд "),
    DOG_SCOTTISH_SETTER("Dog-Scottish Setter / Куче-Шотландски сетер "),
    DOG_SCOTTISH_TERRIER("Dog-Scottish Terrier / Куче-Шотландски териер "),
    DOG_STYRIAN_ROUGH_COLLIE("Dog-Styrian Rough Collie / Куче-Щирийско грубокосместо гонче"),
    DOG_STYRIAN_CROSSBREED("Dog-Styrian Crossbreed / Куче-Щирски брак"),
    DOG_SOUTH_RUSSIAN_SHEPHERD("Dog-South Russian Shepherd / Куче-Южноруска овчарка"),
    DOG_YAGDTERRIER("Dog-Yagdterrier / Куче-Ягдтериер "),
    DOG_JAPANESE_TERRIER("Dog-Japanese Terrier / Куче-Японски териер"),
    DOG_JAPANESE_CHIN("Dog-Japanese Chin / Куче-Японски хин"),
    DOG_JAPANESE_SPITZ("Dog-Japanese Spitz / Куче-Японски шпиц "),
    DOG_MIX("Dog-Mix / Куче-Микс"),
    DOG_OTHERS("Dog-Other / Куче-Друго"),

    CAT_PERSIAN("Cat-Persian / Котка-Персийска котка "),
    CAT_EXOTIC("Cat-Exotic / Котка-Екзотична котка "),
    CAT_COLORPOINT("Cat-Colorpoint / Котка-Колор-пойнт "),
    CAT_STERLING("Cat-Sterling / Котка-Стерлинг "),
    CAT_HIMALAYAN("Cat-Himalayan / Котка-Хималайска котка "),
    CAT_CHINCHILLA("Cat-Chinchilla / Котка-Чинчила "),
    CAT_ASIAN_LONGHAIR_TIFFANY("Cat-Asian Longhair Tiffany / Котка-Азиатска дългокосместа котка Тифани"),
    CAT_AMERICAN_CURL("Cat-American Curl / Котка-Американ кърл "),
    CAT_ANGORA("Cat-Angora / Котка-Ангорска котка"),
    CAT_EXOTIC_SHORTHAIR("Cat-Exotic Shorthair / Котка-Екзотична късокосместа"),
    CAT_CHOCOLATE_YORKIE("Cat-Chocolate Yorkie / Котка-Йоркска шоколадова котка"),
    CAT_ROYAL_ANALOSTOCHNIK("Cat-Royal Analostochnik / Котка-Кралска Аналостанка"),
    CAT_MAINE_COON("Cat-Maine Coon / Котка-Мейн кун "),
    CAT_NEVA_CARNIVAL("Cat-Neva Carnival / Котка-Невска карнавална котка"),
    CAT_NORWEGIAN_FOREST("Cat-Norwegian Forest / Котка-Норвежка горска котка"),
    CAT_WILD_TROJAN("Cat-Wild Trojan / Котка-Дива троянска котка"),
    CAT_PEKING("Cat-Peking / Котка-Пекинска котка"),
    CAT_RAGAMUFFIN("Cat-Ragamuffin / Котка-Рагамъфин"),
    CAT_RAGDOLL("Cat-Ragdoll / Котка-Регдол"),
    CAT_SACRED_BURMESE("Cat-Sacred Burmese / Котка-Свещена бирманска котка"),
    CAT_SIBERIAN("Cat-Siberian / Котка-Сибирска котка"),
    CAT_TIFFANY("Cat-Tiffany / Котка-Тифани "),
    CAT_TURKISH_VAN("Cat-Turkish Van / Котка-Турски ван"),
    CAT_HIGHLAND_STRAIGHT("Cat-Highland Straight / Котка-Хайленд-страйт"),
    CAT_HIGHLAND_FOLD("Cat-Highland Fold / Котка-Хайленд-фолд"),
    CAT_CHANTILLY("Cat-Chantilly / Котка-Шантили"),
    CAT_CHANTILLY_TIFFANY("Cat-Chantilly-Tiffany / Котка-Шантили-Тифани"),
    CAT_ABYSSINIAN("Cat-Abyssinian / Котка-Абисинска котка"),
    CAT_ABITABBI("Cat-Abitabbi / Котка-Абитабби "),
    CAT_AUSTRALIAN_MIST("Cat-Australian Mist / Котка-Австралийска котка Мист"),
    CAT_ASIAN_SHORTHAIR_BURMESE("Cat-Asian Shorthair Burmese / Котка-Азиатска късокосмена Бурма"),
    CAT_ASIAN_SMOKE("Cat-Asian Smoke / Котка-Азиатска опушена"),
    CAT_ASIAN_TABBY("Cat-Asian Tabby / Котка-Азиатска табби"),
    CAT_AMERICAN_SMOOTH("Cat-American Smooth / Котка-Американска гладкокосместа"),
    CAT_AMERICAN_WIRE("Cat-American Wire / Котка-Американска грубокосместа"),
    CAT_AMERICAN_BOBTAIL("Cat-American Bobtail / Котка-Американски бобтейл "),
    CAT_AMERICAN_KURIHAARI("Cat-American Kurihaari / Котка-Американски курихаари "),
    CAT_WHITE_FOOTED_SNOW_SHOE("Cat-White-footed Snow Shoe / Котка-Белоножка Сноу Шу"),
    CAT_BENGAL_CAT("Cat-Bengal cat / Котка-Бенгалска котка"),
    CAT_BOMBAY_CAT("Cat-Bombay cat / Котка-Бомбайска котка"),
    CAT_BOHEMIAN_REX("Cat-Bohemian Rex / Котка-Бохемски рекс"),
    CAT_BRAZILIAN_SHORTHAIR("Cat-Brazilian Shorthair / Котка-Бразилска късокосмена"),
    CAT_BRITISH_SHORTHAIR("Cat-British Shorthair / Котка-Британска късокосместа"),
    CAT_BURMESE_CAT("Cat-Burmese cat / Котка-Бурманска котка"),
    CAT_BURMILLA("Cat-Burmilla / Котка-Бурмила"),
    CAT_GERMAN_REX("Cat-German Rex / Котка-Герман рекс"),
    CAT_DEVON_REX("Cat-Devon Rex / Котка-Девон рекс"),
    CAT_DON_SPHYNX("Cat-Don Sphynx / Котка-Донски сфинкс"),
    CAT_EUROPEAN_CAT("Cat-European cat / Котка-Европейска котка"),
    CAT_EGYPTIAN_MAU("Cat-Egyptian Mau / Котка-Египетска мау"),
    CAT_CALIFORNIA_TABBY_CAT("Cat-California Tabby cat / Котка-Калифорнийска тигрова котка"),
    CAT_CANADIAN_PIXIE_BOB("Cat-Canadian Pixie Bob / Котка-Канадски Пикси Боб"),
    CAT_KARELIAN_BOBTAIL("Cat-Karelian Bobtail / Котка-Карелски бобтейл"),
    CAT_KENYAN_FOREST_CAT("Cat-Kenyan Forest cat / Котка-Кенийска горска котка "),
    CAT_CYMRIC("Cat-Cymric / Котка-Кимрик"),
    CAT_KORAT("Cat-Korat / Котка-Корат"),
    CAT_CORNISH_REX("Cat-Cornish Rex / Котка-Корниш рекс"),
    CAT_KURIL_BOBTAIL("Cat-Kuril Bobtail / Котка-Курилски бобтейл "),
    CAT_LA_PERM("Cat-La Perm / Котка-Ла Перм"),
    CAT_LEOPARD("Cat-Leopard / Котка-Леопардета "),
    CAT_MALAY_CAT("Cat-Malay cat / Котка-Малайска котка"),
    CAT_MANDARIN("Cat-Mandarin / Котка-Мандарин"),
    CAT_MANX("Cat-Manx / Котка-Манкс"),
    CAT_MUNCHKIN("Cat-Munchkin / Котка-Манчкин"),
    CAT_MEXICAN_HAIRLESS_CAT("Cat-Mexican Hairless cat / Котка-Мексиканска гола котка"),
    CAT_NIBELUNG("Cat-Nibelung / Котка-Нибелунг"),
    CAT_OCIKET("Cat-Ociket / Котка-Оцикет"),
    CAT_RUSSIAN_BLUE_CAT("Cat-Russian Blue cat / Котка-Руска синя котка"),
    CAT_SAVANNAH_CAT("Cat-Savannah cat / Котка-Савана"),
    CAT_SAFARI("Cat-Safari / Котка-Сафари"),
    CAT_SELKIRK_REX("Cat-Selkirk Rex / Котка-Селкърк Рекс"),
    CAT_SERENGETI("Cat-Serengeti / Котка-Серенгети"),
    CAT_SINGAPOREAN_CAT("Cat-Singaporean cat / Котка-Сингапурска котка"),
    CAT_SOMALI_CAT("Cat-Somali cat / Котка-Сомали"),
    CAT_SPHINX("Cat-Sphinx / Котка-Сфинкс "),
    CAT_TOYGER("Cat-Toyger / Котка-Тойгър"),
    CAT_WELSH_CARLIN_CAT_BOBTAIL("Cat-Welsh Carlin cat Bobtail / Котка-Уелска котка Карлин Бобтейл"),
    CAT_URAL_REX("Cat-Ural Rex / Котка-Уралски рекс"),
    CAT_FRENCH_STARRY_EYES("Cat-French Starry Eyes / Котка-Френска котка Звездни очи"),
    CAT_CHAUSSEE("Cat-Chaussee / Котка-Чаузи "),
    CAT_CHARTREAUX("Cat-Chartreaux / Котка-Шартрьо"),
    CAT_SCOTTISH_FOLD("Cat-Scottish Fold / Котка-Шотландска клепоуха"),
    CAT_SCOTTISH_STRAIGHT("Cat-Scottish Straight / Котка-Шотландски Страйт"),
    CAT_JAPANESE_CAT_MI_KAY("Cat-Japanese Cat Mi Kay / Котка-Японска котка Ми Кей"),
    CAT_JAPANESE_CAT_PIINAT("Cat-Japanese Cat Piinat / Котка-Японска котка Пийнат"),
    CAT_JAPANESE_BOBTAIL("Cat-Japanese Bobtail / Котка-Японски бобтейл"),
    CAT_BALINESE_CAT("Cat-Balinese Cat / Котка-Балийска котка "),
    CAT_GRUNYA("Cat-Grunya / Котка-Груня "),
    CAT_EBONY("Cat-Ebony / Котка-Ебони "),
    CAT_ORIENTAL_CAT("Cat-Oriental Cat / Котка-Ориенталска котка "),
    CAT_PETERBALD("Cat-Peterbald / Котка-Петерболд "),
    CAT_SEYCHELLES_CAT("Cat-Seychelles Cat / Котка-Сейшелска котка "),
    CAT_SI_KUN("Cat-Si-kun / Котка-Си-кун "),
    CAT_SIAMESE_CAT("Cat-Siamese Cat / Котка-Сиамска котка "),
    CAT_SKIFF_TOY_DON("Cat-Skiff-Toy-Don / Котка-Скиф-той-дон "),
    CAT_THAI_CAT("Cat-Thai Cat / Котка-Тайска котка "),
    CAT_THAI_BOBTAIL("Cat-Thai Bobtail / Котка-Тайски бобтейл "),
    CAT_TONKIN_CAT("Cat-Tonkin Cat / Котка-Тонкинска котка "),
    CAT_FROSTPOINT("Cat-Frostpoint / Котка-Фростпойнт "),
    CAT_HAVANA("Cat-Havana / Котка-Хавана "),
    CAT_HAVANA_BROWN("Cat-Havana Brown / Котка-Хавана браун "),
    CAT_CEYLONESE_CAT("Cat-Ceylonese Cat / Котка-Цейлонска котка "),
    CAT_JAVANESE_CAT("Cat-Javanese Cat / Котка-Яванска котка "),

    RABBIT("Rabbit/Заек"),
    GUINEA_PIG("Guinea Pig/Морско Свинче"),
    PARROT("Parrot/Папагал"),
    CANARY("Canary/Канарче"),
    TURTLE("Turtle/Костенурка"),
    LIZARD("Lizard/Гущер"),
    SNAKE("Snake/Змия"),
    HAMSTER("Hamster/Хамстер"),
    FERRET("Ferret/Фретка"),
    FISH("Fish/Риба"),
    HORSE("Horse/Кон"),
    GOAT("Goat/Коза"),
    SHEEP("Sheep/Овца"),
    CHICKEN("Chicken/Пиле"),
    DUCK("Duck/Патица"),
    IGUANA("Iguana/Игуана"),
    CHINCHILLA("Chinchilla/Чинчила"),
    TARANTULA("Tarantula/Тарантула"),
    HERMIT_CRAB("Hermit Crab/Херметов Рак"),
    AXOLOTL("Axolotl/Аксолотъл"),
    LEOPARD_GECKO("Leopard Gecko/Леопардов Гекон"),
    BEARDED_DRAGON("Bearded Dragon/Брадат дракон"),
    SNAKE_NECK_TURTLE("Snake-neck Turtle/Змиевидна костенурка"),
    PRAIRIE_DOG("Prairie Dog/Прерия"),
    SUGAR_GLIDER("Sugar Glider/Сахарна летяща белка"),
    FENNEC_FOX("Fennec Fox/Фенек"),
    FOX("Fox/Лисица"),
    BEAVER("Beaver/Бобър"),
    WEASEL("Weasel/Невестулка"),
    BELKA("Belka/Белка"),
    SQUIRREL("Squirrel/Катерица"),
    TASMANIAN_DEVIL("Tasmanian Devil/Тасманийски Дявол"),
    KINKAJO("Kinkajou/Кинкаджу"),
    BINTURONG("Binturong/Бинтуронг"),
    COATI("Coati/Коати"),
    GUINEA_FOWL("Guinea Fowl/Гвинейска Патица"),
    MICE("Mice/Мишки"),
    HEDGEHOG("Hedgehog/Таралеж"),
    CHACOAN_PECARY("Chacoan Pecary/Чакско пекари"),
    TORTOISE("Tortoise/Сухоземни костенурки"),
    CATFISH("Catfish/Сом"),
    CROCODILE("Crocodile/Крокодил"),
    ALLIGATOR("Alligator/Алигатор"),
    PANGOLIN("Pangolin/Люспеница"),
    SLOTH("Sloth/Ленивец"),
    CAPYBARA("Capybara/Капибара"),
    MARMOT("Marmot/Мармот"),
    COW("Cow/Крава"),
    PIG("Pig/Прасе"),
    BULL("Bull/Бик"),
    COW_CALF("Calf/Теле"),
    HORSE_FOAL("Foal/Конче"),
    LAMBS("Lamb/Яре"),
    CATTLE("Cattle/Говедо"),
    POULTRY("Poultry/Пиле"),
    TURKEY("Turkey/Пуйка"),
    GUINEA_HEN("Guinea Hen/Гвинейска Пета"),
    PEAFOWL("Peafowl/Паун"),
    MULE("Mule/Муле"),
    DONKEY("Donkey/Магаре"),
    ALPACA("Alpaca/Алпака"),
    LLAMA("Llama/Лама"),
    BISON("Bison/Бизон"),
    YAK("Yak/Як"),
    CAMEL("Camel/Камила"),
    RAT("Rat/Плъх"),
    MUSK_OX("Musk Ox/Мускусен бик"),
    REINDEER("Reindeer/Елен"),
    LIVESTOCK("Livestock/Стоков добитък");
    private final String breed;

    PetType(String breed) {
        this.breed = breed;
    }

    @JsonCreator
    public static PetType fromValue(String value) {
        for (PetType petTypeEnum : values()) {
            String currentPetType = petTypeEnum.getBreed();
            if (currentPetType.equalsIgnoreCase(value)) {
                return petTypeEnum;
            }
        }

        throw new IllegalArgumentException("Invalid value for Pet Type Enum: " + value);
    }

    @JsonValue
    public String getBreed() {
        return breed;
    }
}
